# Generated by Django 5.1.5 on 2025-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0009_adminuser_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('date1', models.DateField(null=True)),
                ('date2', models.DateField(null=True)),
                ('about', models.TextField()),
            ],
        ),
    ]
