# Generated by Django 5.0.6 on 2025-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadesire',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
